const { GoogleGenerativeAI } = require("@google/generative-ai");

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function generateWithGemini(code, language, context = "") {
    try {
      const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro" });
      
      const prompt = `...`; // Your existing prompt
  
      const result = await model.generateContent(prompt);
      const response = await result.response;
      
      if (!response.text) {
        throw new Error('No text generated by Gemini');
      }
      
      return response.text();
    } catch (error) {
      console.error('Gemini Generation Error:', error);
      throw new Error(`Failed to generate documentation: ${error.message}`);
    }
  }

module.exports = { generateWithGemini };